spring:
  jpa:
    #    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        type: trace
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false